version: '3.8'
services:
  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "8081:8081"
  postgres:
    image: 'postgres:15.1-alpine'
    environment:
      - "POSTGRES_DB=petcatalog"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7.2.3-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8082:8081"
    depends_on:
      - redis
  flyway:
    image: flyway/flyway:9.22.3-alpine
    environment:
      - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://postgres:5432/petcatalog -schemas=public -user=admin -password=admin -connectRetries=3 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql/
    depends_on:
      - postgres
  sonarqube:
    image: sonarqube:10.4.0-community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://pg-sonarqube:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonar-network
    depends_on:
      - pg-sonarqube
    restart: unless-stopped
  pg-sonarqube:
    image: 'postgres:15.1-alpine'
    environment:
      - "POSTGRES_DB=sonar"
      - "POSTGRES_PASSWORD=sonar"
      - "POSTGRES_USER=sonar"
    volumes:
      - pg-sonarqube:/var/lib/postgresql/data
    networks:
      - sonar-network
    restart: unless-stopped
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
volumes:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_extensions:
  postgres:
  redis:
  pg-sonarqube:
networks:
  sonar-network:
    driver: bridge