version: '3.8'
services:
  db:
    image: 'postgres:15.1-alpine'
    environment:
      - 'POSTGRES_DB=petcatalog'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local