server:
  port: 8080
management:
  server:
    port: 8081
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    probes:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springtools
    password: ${DATABASE_USERNAME}
    username: ${DATABASE_PASSWORD}
    hikari:
      connectionTimeout: 2000
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    cache-names: users
logging:
  level:
    root: ERROR
    org.springframework.boot: ERROR
    com.gt.springtools: DEBUG
cache:
  config:
    entryTtl: 1
    users:
      entryTtl: 1
tracing:
  url: http://localhost:4317
resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 15
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 30
      permittedNumberOfCallsInHalfOpenState: 20
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50