server:
  port: 8080
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petcatalog
    password: admin
    username: admin
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: ERROR
    org.springframework.boot: ERROR
    com.gt.petcatalog: DEBUG
