server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,liveness,readiness
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/petcatalog
    password: admin
    username: admin
  redis:
    host: ${HOST:localhost}
    port: ${PORT:6379}
  cache:
    type: redis
    cache-names: users
logging:
  level:
    root: ERROR
    org.springframework.boot: ERROR
    com.gt.petcatalog: DEBUG
cache:
  config:
    entryTtl: 10
    users:
      entryTtl: 5