server:
  port: 8080
management:
  server:
    port: 8081
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,liveness,readiness,metrics
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    probes:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/springtools
    password: admin
    username: admin
    hikari:
      connectionTimeout: 2000
  flyway:
    enabled: false
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    cache-names: users
logging:
  level:
    root: ERROR
    org.springframework.boot: ERROR
    com.gt.springtools: INFO
cache:
  config:
    entryTtl: 30
    users:
      entryTtl: 15
tracing:
  url: http://jaeger:4317
resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 100
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 50
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 30s
      failureRateThreshold: 30