server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springtools
    password: admin
    username: admin
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    cache-names: users
logging:
  level:
    root: ERROR
    org.springframework.boot: ERROR
    com.gt.springtools: DEBUG
cache:
  config:
    entryTtl: 1
    users:
      entryTtl: 1