server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,liveness,readiness,metrics
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springtools
    password: admin
    username: admin
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    cache-names: users
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: ERROR
    org.springframework.boot: ERROR
    com.gt.springtools: DEBUG
cache:
  config:
    entryTtl: 60
    users:
      entryTtl: 30